
version: '3.5'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: gancio
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data

  app:
    env_file: .env
    build: .
    ports:
      - '12300:12300'
    volumes:
      - ./app/uploads:/usr/src/app/app/uploads

    environment:
      PORT: 12300
      DB_HOST: db
      DB_PASS: 12345
      DB_USER: postgres
      DB_NAME: gancio

    links:
      - db

