version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=gancio
      - POSTGRES_DB=gancio
      - POSTGRES_PASSWORD=gancio
      - PGDATA=/var/lib/postgresql/data
    restart: always
    ports:
        - 5432:5432
  gancio:
    build: .
    restart: always
    image: node:buster
    container_name: gancio
    environment:
      - PATH=$PATH:/home/node/.yarn/bin
      - GANCIO_DATA=/home/node/data
      - NODE_ENV=production
    command: gancio start --docker
    entrypoint: /entrypoint.sh
    volumes:
      - ./data:/home/node/data
    ports:
      - "127.0.0.1:13120:13120"
    depends_on:
        - db
