# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gancio
email: lesion@autistici.org
description: >- # this means to ignore newlines until "baseurl:"
        A shared agenda for local communities with AP support
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gancio.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: "just-the-docs"
plugins:
  - jekyll-feed
  - jemoji
  - premonition
  - jekyll-default-layout

search_enabled: true

aux_links:
  "Blog":
    - https://blog.gancio.org
  "Source":
    - https://framagit.org/les/gancio
  "Mastodon":
    - https://mastodon.cisti.org/@gancio

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page"
gh_edit_repository: "https://framagit.org/les/gancio" # the github URL for your repo
gh_edit_branch: "master/docs" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "-/tree" # "tree" or "edit" if you want the user to jump into the editor immediately



#Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
